# Generated by Django 3.0.2 on 2020-01-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='desc',
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=100, help_text='Height in m.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=100, help_text='Weight in Kgs.'),
            preserve_default=False,
        ),
    ]
